# Copyright (c) 2025 Cafesuada
# All rights reserved.

/ros_arduino_bridge:
  ros__parameters:
    serial_port: '/dev/ttyUSB0'
    baudrate: 57600
    serial_timeout_ms: 1000
    encoder_resolution: 20
    wheel_diameter_meter: 0.065
