llm_client:
  ros__parameters:
    gemini_model: 'gemini-2.5-flash'

    streamable_http:
      use_https: False
      host: '127.0.0.1'
      port: 8000
      path: 'mcp'

streamablehttp_mcp_server:
  ros__parameters:
    host: '127.0.0.1'
    port: 8000


      

