# Copyright (c) 2025 Cafesuada
# All rights reserved.

uint16 map_id
string query
uint32 k
---
bool success
string message
string[] ids
string[] names
float64[] xs
float64[] ys
float64[] yaws
float64[] distances
