controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    wheel_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_controller:
  ros__parameters:
    publish_rate: 50.0

    enable_odom_tf: false

    left_wheel_names: ['wheel_front_left_joint']
    right_wheel_names: ['wheel_front_right_joint']

    wheel_separation: 0.137
    # wheel_separation: 0.1325 # real value
    wheel_radius: 0.0325

    linear.x.max_velocity: 0.8
    linear.x.min_velocity: -0.35
    linear.x.max_acceleration: 3.5
    linear.x.max_deceleration: -3.5
    linear.x.max_acceleration_reverse: -1.0
    linear.x.max_deceleration_reverse: 1.0
    
    # odom_frame_id: odom
    # base_frame_id: base_link
  

