# Copyright (c) 2025 Cafesuada
# All rights reserved.

/twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      keyboard:
        topic: /key_cmd_vel
        timeout: 0.5
        priority: 10
      joy:
        topic: /joy_cmd_vel
        timeout: 0.5
        priority: 10
      navigation:
        topic: /nav_cmd_vel
        timeout: 0.5
        priority: 20
