<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aether_bringup</name>
  <version>0.1.0</version>
  <description>Bringup scripts and configuration for Aether robot</description>
  <maintainer email="108068915+cafesuada24@users.noreply.github.com">Cafesuada</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>geometry_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>aether_navigation</exec_depend>
  <exec_depend>aether_description</exec_depend>
  <exec_depend>aether_driver</exec_depend>
  <exec_depend>aether_webserver</exec_depend>
  <exec_depend>aether_agent</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>v4l2_camera</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
